apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sae-ui-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/hepapi/helm-base-common.git'
      path: 'v1.32'
      targetRevision: 'main'
      helm:
        releaseName: sae-ui-dev
        valueFiles:
          - $values-repo/non-prod/dev/sae-ui-dev-values.yaml

    - repoURL: 'https://github.com/hepapi/app-values.git'
      targetRevision: 'main'
      ref: values-repo
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sae-dev

  info:
    - name: 'Github Repo'
      value: 'https://github.com/hepapi/sae-ui-dev.git'
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:     
      - Validate=false 
      - CreateNamespace=true 
      - PrunePropagationPolicy=foreground 
      - PruneLast=true 
      - ApplyOutOfSyncOnly=true 

  revisionHistoryLimit: 5
